{% set name = "harmonica" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d0e508675996cec171c704ae30199a2bc0f1c0b81b2f50a56558442440c92888

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - numpy
    - scipy
    - scikit-learn
    - pandas
    - xarray
    - numba
    - pooch >=0.7.0
    - verde >=1.5.0

test:
  imports:
    - harmonica

about:
  home: http://github.com/fatiando/harmonica
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Processing and modeling gravity and magnetic data
  description: |
    Harmonica is a Python library for processing and modeling gravity and
    magnetic data. It includes common processing steps, like calculation of
    Bouguer and terrain corrections, reduction to the pole, upward
    continuation, equivalent layers, and more. There are forward modeling
    functions for basic geometric shapes, like spheres, prisms, polygonal
    prisms, and tesseroids. The inversion methods are implemented as classes
    with an interface inspired by scikit-learn (like Verde).
  doc_url: https://www.fatiando.org/harmonica
  dev_url: https://github.com/fatiando/harmonica

extra:
  recipe-maintainers:
    - leouieda
    - santisoler
