{% set name = "harmonica" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a4f889b121778479a87d94e481c423e51dd4355593fbab497ad357c0c7fa219a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - numpy >=1.19
    - scipy >=1.5
    - scikit-learn >=0.24
    - pandas >=1.1
    - xarray >=0.16
    - numba >=0.52
    - verde >=1.7
    - xrft >=1.0

test:
  imports:
    - harmonica

about:
  home: http://github.com/fatiando/harmonica
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Processing and modeling gravity and magnetic data
  description: |
    Harmonica is a Python library for processing and modeling gravity and
    magnetic data. It includes common processing steps, like calculation of
    Bouguer and terrain corrections, reduction to the pole, upward
    continuation, equivalent layers, and more. There are forward modeling
    functions for basic geometric shapes, like spheres, prisms, polygonal
    prisms, and tesseroids. The inversion methods are implemented as classes
    with an interface inspired by scikit-learn (like Verde).
  doc_url: https://www.fatiando.org/harmonica
  dev_url: https://github.com/fatiando/harmonica

extra:
  recipe-maintainers:
    - leouieda
    - santisoler
